all:
	gcc -o linkedlistExample linkedlistExample.c serialize.c
	gcc -o treeExample treeExample.c serialize.c

listEx:
	gcc -o linkedlistExample linkedlistExample.c serialize.c
	
treeEx:
	gcc -o treeExample treeExample.c serialize.c
